In [2]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 19.8 ms, sys: 18.6 ms, total: 38.4 ms
Wall time: 36.9 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 568 ms, sys: 94.8 ms, total: 663 ms
Wall time: 664 ms


### 4.1 The NumPy ndarray: A Multidimensional Array Object

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.16632703, -1.83105701,  0.26090113],
       [ 0.67361233,  0.06975718,  0.32618885]])

In [8]:
data * 10

array([[ -1.66327027, -18.31057011,   2.60901128],
       [  6.7361233 ,   0.69757185,   3.26188852]])

In [9]:
data + data

array([[-0.33265405, -3.66211402,  0.52180226],
       [ 1.34722466,  0.13951437,  0.6523777 ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### Creating ndarrays

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 2.37151510e-322],
        [0.00000000e+000, 0.00000000e+000],
        [5.21501686e-310, 1.61590357e+184]],

       [[6.86671398e-091, 2.03890577e+160],
        [1.00527912e-047, 2.44748117e-056],
        [3.99910963e+252, 1.46030983e-319]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr1

array([1., 2., 3.])

In [30]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int64')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [37]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [38]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [39]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [40]:
int_array = np.arange(10)

In [41]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [42]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
empty_unit32 = np.empty(8, dtype='u4')

In [44]:
empty_unit32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

### Arithmetic with NumPy Arrays

In [45]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [46]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [47]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [48]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [50]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [52]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [53]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [55]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [57]:
arr = np.arange(10)

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[5]

5

In [60]:
arr[5:8]

array([5, 6, 7])

In [61]:
arr[5:8]

array([5, 6, 7])

In [62]:
arr[5:8] = 12

In [63]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
arr_slice = arr[5:8]

In [65]:
arr_slice

array([12, 12, 12])

In [66]:
arr_slice[1] = 12345

In [67]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [68]:
arr_slice[:] = 64

In [69]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [20]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [72]:
arr2d[2]

array([7, 8, 9])

In [74]:
arr2d[0][2]

3

In [75]:
arr2d[0, 2]

3

In [3]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [4]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
old_values = arr3d[0].copy()

In [7]:
arr3d[0] = 42

In [8]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
arr3d[0] = old_values

In [10]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr3d[1, 0]

array([7, 8, 9])

In [12]:
x = arr3d[1]

In [13]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [14]:
x[0]

array([7, 8, 9])

In [15]:
arr

NameError: name 'arr' is not defined

In [16]:
arr = np.array([0, 1, 2, 3, 4, 64, 64, 64, 8, 9])

In [17]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [18]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [24]:
arr2d[1, :2]

array([4, 5])

In [25]:
arr2d[:2, 2]

array([3, 6])

In [26]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [27]:
arr2d[:2, 1:] = 0

In [28]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [30]:
data = np.random.randn(7, 4)

In [31]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [32]:
data

array([[-0.22349804, -2.57972509,  0.85473202,  1.68863868],
       [ 0.40475508, -0.45539086,  0.53586495, -1.11965927],
       [ 0.02817242, -2.30467477,  0.8120172 ,  0.24398721],
       [-1.23691998,  0.79951519,  0.32166858, -0.20398652],
       [-0.68460113, -0.11146738, -1.06724619, -1.02400548],
       [ 0.68301153, -0.94915636,  2.52491535, -1.79501104],
       [ 0.71849305,  0.96633929, -1.23989726,  0.24642423]])

In [33]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [34]:
data[names == 'Bob']

array([[-0.22349804, -2.57972509,  0.85473202,  1.68863868],
       [-1.23691998,  0.79951519,  0.32166858, -0.20398652]])

In [35]:
data[names == 'Bob', 2:]

array([[ 0.85473202,  1.68863868],
       [ 0.32166858, -0.20398652]])

In [36]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [37]:
data[~(names == 'Bob')]

array([[ 0.40475508, -0.45539086,  0.53586495, -1.11965927],
       [ 0.02817242, -2.30467477,  0.8120172 ,  0.24398721],
       [-0.68460113, -0.11146738, -1.06724619, -1.02400548],
       [ 0.68301153, -0.94915636,  2.52491535, -1.79501104],
       [ 0.71849305,  0.96633929, -1.23989726,  0.24642423]])

In [38]:
data[names != 'Bob']

array([[ 0.40475508, -0.45539086,  0.53586495, -1.11965927],
       [ 0.02817242, -2.30467477,  0.8120172 ,  0.24398721],
       [-0.68460113, -0.11146738, -1.06724619, -1.02400548],
       [ 0.68301153, -0.94915636,  2.52491535, -1.79501104],
       [ 0.71849305,  0.96633929, -1.23989726,  0.24642423]])

In [39]:
cond = names == 'Bob'

In [40]:
data[~cond]

array([[ 0.40475508, -0.45539086,  0.53586495, -1.11965927],
       [ 0.02817242, -2.30467477,  0.8120172 ,  0.24398721],
       [-0.68460113, -0.11146738, -1.06724619, -1.02400548],
       [ 0.68301153, -0.94915636,  2.52491535, -1.79501104],
       [ 0.71849305,  0.96633929, -1.23989726,  0.24642423]])

In [41]:
mask = (names == 'Bob') | (names == 'Will')

In [42]:
mask

array([ True, False,  True,  True,  True, False, False])

In [43]:
data[mask]

array([[-0.22349804, -2.57972509,  0.85473202,  1.68863868],
       [ 0.02817242, -2.30467477,  0.8120172 ,  0.24398721],
       [-1.23691998,  0.79951519,  0.32166858, -0.20398652],
       [-0.68460113, -0.11146738, -1.06724619, -1.02400548]])

In [44]:
data[data < 0] = 0

In [45]:
data

array([[0.        , 0.        , 0.85473202, 1.68863868],
       [0.40475508, 0.        , 0.53586495, 0.        ],
       [0.02817242, 0.        , 0.8120172 , 0.24398721],
       [0.        , 0.79951519, 0.32166858, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.68301153, 0.        , 2.52491535, 0.        ],
       [0.71849305, 0.96633929, 0.        , 0.24642423]])

In [46]:
data[names != 'Joe'] = 7

In [47]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.40475508, 0.        , 0.53586495, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.68301153, 0.        , 2.52491535, 0.        ],
       [0.71849305, 0.96633929, 0.        , 0.24642423]])

### Fancy Indexing

In [48]:
arr = np.empty((8, 4))

In [49]:
for i in range(8):
    arr[i] = i

In [50]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [51]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [52]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [53]:
arr = np.arange(32).reshape((8, 4))

In [54]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [55]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [56]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

#### Transposing Arrays and Swapping Axes

In [57]:
arr = np.arange(15).reshape((3, 5))

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [60]:
arr = np.random.randn(6, 3)

In [61]:
arr

array([[ 0.94611015, -1.26895183, -0.91636901],
       [ 0.69867899,  0.8719544 ,  0.94117615],
       [-1.0324089 , -0.0674162 ,  0.18709495],
       [ 1.74423538, -1.98047187, -0.46008858],
       [ 2.00206526,  0.12490731,  0.77450802],
       [ 0.29528137,  0.79160237,  1.52525064]])

In [62]:
np.dot(arr.T, arr)

array([[ 9.58695831, -3.49234198,  0.79592639],
       [-3.49234198,  6.93959314,  4.18620381],
       [ 0.79592639,  4.18620381,  4.89848292]])

In [63]:
arr = np.arange(16).reshape((2, 2, 4))

In [64]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [65]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [66]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [67]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])