In [1]:
import pandas as pd

## 5.1 Introduction to pandas Data Structures

### Series

In [2]:
obj = pd.Series([4, 7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [7]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
obj2['a']

-5

In [10]:
obj2['d'] = 6

In [11]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
np.exp?

Call signature:  np.exp(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'exp'>
File:            ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:      
exp(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the exponential of all elements in the input array.

Parameters
----------
x : array_like
    Input values.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.


In [18]:
'b' in obj2

True

In [19]:
12 in obj2

False

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [30]:
obj3 = pd.Series(sdata)

In [31]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [33]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [35]:
obj4.index.name = 'state'

In [36]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [39]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [40]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [41]:
frame = pd.DataFrame(data)

In [42]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [43]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [44]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])

In [46]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [49]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [50]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2['debt'] = 16.5

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [53]:
frame2['debt'] = np.arange(6.)

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [55]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [56]:
frame2['debt'] = val

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [58]:
frame2['eastern'] = frame2.state == 'Ohio'

In [59]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [60]:
del frame2['eastern']

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [62]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [63]:
pop = {'Nevada': {2001:2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [64]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [65]:
frame3 = pd.DataFrame(pop)

In [66]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [67]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [68]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [69]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [70]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [71]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [72]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [73]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [74]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [75]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [76]:
index = obj.index

In [77]:
index

Index(['a', 'b', 'c'], dtype='object')

In [78]:
obj.values

array([0, 1, 2])

In [79]:
index[1:]

Index(['b', 'c'], dtype='object')

In [80]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [81]:
labels = pd.Index(np.arange(3))

In [82]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [83]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [84]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [85]:
obj2.index is labels

True

In [86]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [87]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [88]:
'Ohio' in frame3.columns

True

In [89]:
2003 in frame3.index

False

In [90]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [91]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 Essential Functionality

### Reindexing

In [92]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [93]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [94]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [95]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [96]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [97]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [98]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [99]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), 
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [100]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [101]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [102]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [103]:
states = ['Texas', 'Utah', 'California']

In [104]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [105]:
frame.reindex(index=['a', 'b', 'c', 'd'], columns=states)
# frame.loc[['a', b', 'c', 'd'], states] is depreciated..

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis

In [106]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [107]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [108]:
new_obj = obj.drop('c')

In [109]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [110]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [111]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [112]:
data = pd.DataFrame(np.arange(16).reshape(4, 4), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [113]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [115]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [117]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [118]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [119]:
obj.drop('c', inplace=True)

In [120]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [121]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [122]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [123]:
obj['b']

1.0

In [124]:
obj[1]

1.0

In [125]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [126]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [127]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [128]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [129]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [130]:
obj['b':'c'] = 5

In [131]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [132]:
data = pd.DataFrame(np.arange(16).reshape(4, 4), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [133]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [135]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [136]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [137]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [139]:
data[data < 5] = 0

In [140]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

axis labels : loc
integers : iloc

In [141]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [142]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [143]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [144]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [145]:
data.loc[: 'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [146]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [147]:
ser = pd.Series(np.arange(3.))

In [148]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [149]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [150]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [151]:
ser2[-1]

2.0

In [152]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [153]:
ser[:1]

0    0.0
dtype: float64

In [154]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [155]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [156]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [157]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [158]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [159]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [160]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [161]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado'])

In [162]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [163]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [164]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [165]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [166]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [167]:
df1

A
0  1
1  2

In [168]:
df2

B
0  3
1  4

In [169]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [170]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abcde'))

In [171]:
df2.loc[1, 'b'] = np.nan

In [172]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [173]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [174]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [175]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [177]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [178]:
df1.reindex(columns=df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

##### Operations between DataFrame and Series

In [179]:
arr = np.arange(12.).reshape((3, 4))

In [180]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [181]:
arr[0]

array([0., 1., 2., 3.])

In [182]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [183]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [184]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [185]:
series = frame.iloc[0]

In [186]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [187]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [188]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [189]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [190]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [191]:
series3 = frame['d']

In [192]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [193]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [194]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [196]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [197]:
frame

b         d         e
Utah   -0.083991  0.080703  0.992439
Ohio    1.042621  0.349229 -0.287271
Texas   0.280030 -0.707920  2.386411
Oregon  0.127028 -2.136384  0.355318

In [198]:
np.abs(frame)

b         d         e
Utah    0.083991  0.080703  0.992439
Ohio    1.042621  0.349229  0.287271
Texas   0.280030  0.707920  2.386411
Oregon  0.127028  2.136384  0.355318

In [199]:
f = lambda x: x.max() - x.min()

In [200]:
frame.apply(f)

b    1.126613
d    2.485613
e    2.673682
dtype: float64

In [201]:
frame.apply(f, axis='columns')

Utah      1.076430
Ohio      1.329892
Texas     3.094331
Oregon    2.491702
dtype: float64

In [202]:
frame.apply(f, axis=0)

b    1.126613
d    2.485613
e    2.673682
dtype: float64

In [203]:
frame.apply(f, axis=1)

Utah      1.076430
Ohio      1.329892
Texas     3.094331
Oregon    2.491702
dtype: float64

In [204]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [205]:
frame.apply(f)

b         d         e
min -0.083991 -2.136384 -0.287271
max  1.042621  0.349229  2.386411

In [207]:
format = lambda x: '%.2f' % x

In [208]:
frame.applymap(format)

b      d      e
Utah    -0.08   0.08   0.99
Ohio     1.04   0.35  -0.29
Texas    0.28  -0.71   2.39
Oregon   0.13  -2.14   0.36

In [209]:
frame['e'].map(format)

Utah       0.99
Ohio      -0.29
Texas      2.39
Oregon     0.36
Name: e, dtype: object

### Sorting and Ranking

In [210]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [211]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [212]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [213]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [214]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [215]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [216]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [219]:
frame.sort_values(by='a')

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [220]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [221]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [222]:
obj = pd.Series([4, 7, -3, 2])

In [223]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [224]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [225]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [226]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [227]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, 1]})

In [228]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [229]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [230]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [231]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [232]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [233]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [234]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [235]:
frame = pd.DataFrame({'b':[4.3, 7, -3, 2], 'a':[0, 1, 0, 1], 'c':[-2, 5, 8, -2.5]})

In [236]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [237]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis Indexes with Duplicate Labels

In [238]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [239]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [240]:
obj.index.is_unique

False

In [241]:
obj['a']

a    0
a    1
dtype: int64

In [242]:
obj['c']

4

In [243]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [244]:
df

0         1         2
a -0.836012  0.336673  0.577182
a  1.775066 -0.258396 -0.263605
b  0.190681  0.367735  1.073939
b  0.998553 -0.152276  1.257680

In [245]:
df.loc['b']

0         1         2
b  0.190681  0.367735  1.073939
b  0.998553 -0.152276  1.257680

## 5.3 Summarizing and Computing Descriptive Statistics

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
                   [np.nan, np.nan], [0.75, -1.3]], 
                  index=['a', 'b', 'c', 'd'], 
                  columns=['one', 'two'])

In [3]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [4]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [5]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [6]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [7]:
df.sum(axis='rows')

one    9.25
two   -5.80
dtype: float64

In [8]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [9]:
df.mean(axis='columns', skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [10]:
df.idxmax()

one    b
two    d
dtype: object

In [12]:
df.idxmin()

one    d
two    b
dtype: object

In [13]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [14]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [16]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [17]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [18]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [19]:
import pandas_datareader.data as web

In [21]:
all_data = {ticker: web.get_data_yahoo(ticker) 
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [22]:
all_data


{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2016-12-13  115.919998  113.750000  113.839996  115.190002   43733811.0   
 2016-12-14  116.199997  114.980003  115.040001  115.190002   34031834.0   
 2016-12-15  116.730003  115.230003  115.379997  115.820000   46524544.0   
 2016-12-16  116.500000  115.644997  116.470001  115.970001   44351134.0   
 2016-12-19  117.379997  115.750000  115.800003  116.639999   27779423.0   
 ...                ...         ...         ...         ...          ...   
 2021-12-06  167.879898  164.279999  164.289993  165.320007  107496982.0   
 2021-12-07  171.580002  168.339996  169.080002  171.179993  120405352.0   
 2021-12-08  175.960007  170.699997  172.125000  175.080002  116998901.0   
 2021-12-09  176.750000  173.919998  174.910004  174.559998  108923739.0   
 2021-12-10  179.630005  174.690002  175.205002  179.449997  110986702.0   
 
  

In [24]:
price = pd.DataFrame({ticker: data['Adj Close'] for ticker, data in all_data.items()})

In [25]:
volume = pd.DataFrame({ticker: data['Volume'] for ticker, data in all_data.items()})

In [26]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2016-12-13  112.414299  133.799866   58.557430   796.099976
2016-12-14  112.414299  133.974762   58.278496   797.070007
2016-12-15  113.029106  133.585159   58.185528   797.849976
2016-12-16  113.175491  132.559555   57.925179   790.799988
2016-12-19  113.829338  132.519791   59.152477   794.200012
...                ...         ...         ...          ...
2021-12-06  165.320007  119.910004  326.190002  2875.929932
2021-12-07  171.179993  121.580002  334.920013  2960.729980
2021-12-08  175.080002  123.019997  334.970001  2974.409912
2021-12-09  174.559998  123.570000  333.100006  2962.120117
2021-12-10  179.449997  124.089996  342.540009  2973.500000

[1258 rows x 4 columns]

In [27]:
returns = price.pct_change()

In [28]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-12-06  0.021503  0.009004  0.009845  0.008953
2021-12-07  0.035446  0.013927  0.026764  0.029486
2021-12-08  0.022783  0.011844  0.000149  0.004620
2021-12-09 -0.002970  0.004471 -0.005583 -0.004132
2021-12-10  0.028013  0.004208  0.028340  0.003842

In [29]:
returns['MSFT'].corr(returns['IBM'])

0.5046489356888298

In [30]:
returns['MSFT'].cov(returns['IBM'])

0.00014517339606627937

In [31]:
returns.MSFT.corr(returns.IBM)

0.5046489356888298

In [32]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.282963  0.480455  0.438140
IBM   0.282963  1.000000  0.504649  0.473122
MSFT  0.480455  0.504649  1.000000  0.772142
GOOG  0.438140  0.473122  0.772142  1.000000

In [33]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000820  0.000135  0.000237  0.000212
IBM   0.000135  0.000278  0.000145  0.000134
MSFT  0.000237  0.000145  0.000297  0.000225
GOOG  0.000212  0.000134  0.000225  0.000287

In [34]:
returns.corr() ** 2

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.080068  0.230837  0.191967
IBM   0.080068  1.000000  0.254671  0.223845
MSFT  0.230837  0.254671  1.000000  0.596204
GOOG  0.191967  0.223845  0.596204  1.000000

In [35]:
returns.corrwith(returns.IBM)

AAPL    0.282963
IBM     1.000000
MSFT    0.504649
GOOG    0.473122
dtype: float64

In [36]:
returns.corrwith(volume)

AAPL   -0.043858
IBM    -0.140336
MSFT   -0.062781
GOOG   -0.111375
dtype: float64

### Unique Values, Value Counts, and Membership

In [37]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [38]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [39]:
uniques = obj.unique()

In [40]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [41]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [42]:
uniques.sort

<function ndarray.sort>

In [43]:
uniques.sort()

In [44]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [45]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [46]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [47]:
mask = obj.isin(['b', 'c'])

In [48]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [49]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [50]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [51]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [52]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [53]:
pd.Index(unique_vals)

Index(['c', 'b', 'a'], dtype='object')

In [54]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 
                     'Qu2': [2, 3, 1, 2, 3], 
                     'Qu3': [1, 5, 2, 4, 4]})

In [55]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [56]:
result = data.apply(pd.value_counts).fillna(0)

In [57]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [58]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [59]:
data.apply(pd.value_counts)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [60]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0